[package]
name = "socketpioneer"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
crossterm = "0.27.0"
ratatui = "0.25.0"
stomp-rs = "0.0.8"
tungstenite = {version = "0.21.0", features  = ["native-tls"]} 
